name: Validate LinkML Data

on:
    pull_request:
        paths:
            - "stamped-principles-schema.yaml"
            - "stamped-principles.json"
            - ".github/workflows/validate.yml"
    workflow_dispatch:

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install LinkML
              run: pip install linkml

            - name: Validate checklist
              run: linkml-validate --schema ./stamped-principles-schema.yaml --target-class PrincipleSet ./stamped-principles.json
